runtime: python37
env: standard
basic_scaling:
  max_instances: 5
  idle_timeout: 10m
env_variables:
  ## Put production environment variables here.
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
instance_class: B8
  
