runtime: python37
env: standard
env_variables:
  ## Put production environment variables here.
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
instance_class: F4_1G
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
